<Wait>:
    name: 'wait'
    please_wait: please_wait
    Image:
        source: 'Images/004.jpg'
    Image:
        source: 'Images/006.png'
        pos_hint: {'center_x': .5, 'center_y': .6}
    Label:
        id: please_wait
        text: 'Waiting for {}'.format(root.team)
        font_name: 'MyriadPro'
        font_size: dp(20)
        color: 1, 1, 1, 1
        pos_hint: {'center_x': .5, 'center_y': .3}